services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
  identity-svc:
    image: rasr88/identity-svc:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - IDENTITY_DB=Server=postgres:5432;User Id=postgres;Password=postgrespw;Database=identitydb
      - CLIENT_APP=http://localhost:3000
    ports:
      - 5000:80
    depends_on:
      - postgres
volumes:
   redis-data: